# Reusable workflow for the repositories of the Arcalot organization.
# This workflow builds a Go release.
#
# It builds either a "release" or a "snapshot" (depending on the value of the
# `for_release` input, which should be set to true or false, respectively) and
# uploads the resulting binary artifacts.
#
# (It is only run when invoked by another workflow.)
on:
  workflow_call:
    inputs:
      for_release:
        required: true
        type: boolean
      go_version:
        required: true
        type: string
    secrets:
      QUAY_USERNAME:
        required: false
      QUAY_PASSWORD:
        required: false
env:
  do_login: ${{ secrets.QUAY_USERNAME != '' }}
jobs:
  build:
    name: build ${{ inputs.for_release && 'release' || 'snapshot' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go_version }}
      - name: Login to Quay.io
        if: do_login && startsWith(github.event.ref, 'refs/tags/')
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Build ${{ inputs.for_release && 'release' || 'snapshot' }}
        uses: goreleaser/goreleaser-action@v5
        env:
          GITHUB_TOKEN: ${{ inputs.for_release && secrets.GITHUB_TOKEN || '' }}
          GOPROXY: direct
          GOSUMDB: off
          ARGS: ${{ inputs.for_release && 'release --clean' || 'build --snapshot' }}
        with:
          distribution: goreleaser
          version: latest
          args: ${{ env.ARGS }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: dist
